### PR TITLE
Changing image size view model to make it work with Magento 2.4.1

### PR DESCRIPTION
**Pull request by santibm**
The view model didn't really work when installed in a Magento 2.4.1, haven't verified if it is a specific version issue, but the image path was not correct

### CODE REVIEW

**Comment by jochhop** [comment]
Thanks for your contribution @santibm , we'll check it and let you know

**Comment by akai-z** [comment]
I was not able to replicate the issue on a newly installed Magento `2.4.1` (and `2.4.0`) website.  
The category image path was correct, and the view model was able to return the image size.

I also tested the code submitted in this pull request, but it returned an error due to incorrect image path:
```
Uncaught Exception: Warning: getimagesize(/web/pub/media/catalog/category//media/catalog/category/image.jpg): failed to open stream: No such file or directory
```
That's because [`$category->getImage()`](https://github.com/SnowdogApps/magento2-category-attributes/blob/8dc9934ce82f9dff11306463dfaa0b79ab0c63c5/ViewModel/ImageSize.php#L32) already includes the path `/media/catalog/category/`.

**Comment by jochhop** [comment]
Hi @santibm please check the above comment, per our tests, it seems the current code works ok, so please let us know if there's some specific way to test it to get your issue? Maybe it's related to some invalid server config rewrite in your case (nginx, apache)?

**Comment by santibm** [comment]
Strange, then is probably an environment issue as you say, in our site, $category->getImage() doesn't include the path as you can see: 

Screen Shot 2020-11-11 at 08 26 51

**Comment by jochhop** [comment]
Hi again @santibm, we have double checked it, and indeed in a clear Magento Open Source 2.4.x installation (we have tested 2.4.0 and 2.4.1), the category images are being stored in database with the prefix: `/media/catalog/category/`, therefore it should be an issue in your specific installation.

Please double check it in a clean Magento 2.4.x installation and see if you get the desired result.

Thanks in advance.

**Comment by akai-z** [comment]
I checked Magento (`2.4.1`) catalog module category image related code,  
and found that part of the image URL methods code handles image value when it's just an image name and not a relative path. For example:  
[Here](https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/Catalog/Model/Category.php#L687-L692). 
[And here](https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/Catalog/Model/Category/Image.php#L62-L64).  
(Where [\Magento\Catalog\Model\Category\FileInfo::ENTITY_MEDIA_PATH](https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/Catalog/Model/Category/FileInfo.php#L23-L26) value is `/catalog/category`.)

The image upload code could be found [here](https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/Catalog/Model/Category/Attribute/Backend/Image.php#L125-L168).
However, I still did not manage to produce a case where uploaded image attribute value is just an image name.

But I found one case where Magento seems to store category image name only, without media directory path, and that's in Magento [2.2.11](https://github.com/magento/magento2/blob/2.2.11/app/code/Magento/Catalog/Model/Category.php#L696-L698).
And the image upload code for Magento `2.2.11` could be found [here](https://github.com/magento/magento2/blob/2.2.11/app/code/Magento/Catalog/Model/Category/Attribute/Backend/Image.php#L108-L131).

So if the DB contains category images that were stored on Magento `2.2.x` or older,  
then that could be a possible reason why those image attribute values are file names only.

I think we could change it in this module just like in the newer Magento releases (`2.3.x` and `2.4.x`) examples mentioned above,  
and handle both image attribute value cases (with or without media directory path).

**Comment by jochhop** [comment]
Please @santibm see the detailed comment above, as a summary, we can just implement both approaches:

- One will be used when `getImage()` includes `media` path
- 2nd one when `getImage()` does not include `media` path

would you like to update your PR to include such changes? or do you prefer us to take a look instead?

**Comment by santibm** [comment]
Hi! 

Thanks for investigating it, I just checked the db of two different installs (2.2.6 and 2.3.5) and the images are stored without a path: 

Screen Shot 2020-11-14 at 18 43 30

Screen Shot 2020-11-14 at 18 43 24

I'm really late with some work so if you can have a look to it that would be great!!

**Comment by jochhop** [comment]
Hi @santibm so we finished the work in the related PR, the changes were merged to develop and a new release was created, please update your module to `1.3.0` version to see the results,

Thanks for your contribution and have a nice day

**Pull request closed without merging**
